async function K(q){try{console.log("[generator] Starting MHTML generation");let w=await X(q);console.log("[generator] Collected resources:",w.length);let k=N(q);console.log("[generator] Created header:",k);let F=V(q);console.log("[generator] Main content length:",F.length);let A=w.map(W);console.log("[generator] Resource parts:",A.length);let z=[k,`--REPUBFOX-MHTML-BOUNDARY\r
${F}`,...A.map((I)=>`--REPUBFOX-MHTML-BOUNDARY\r
${I}`),`--REPUBFOX-MHTML-BOUNDARY--\r
`].join(`\r
`);return console.log("[generator] MHTML structure (first 500 chars):",z.substring(0,500)),new TextEncoder().encode(z)}catch(w){throw console.error("[generator] Error generating MHTML:",w),w}}function N(q){let w=q.location.href,k=["From: Saved by RepubFox","Subject: "+q.title,"Date: "+new Date().toUTCString(),"MIME-Version: 1.0",'Content-Type: multipart/related; boundary="REPUBFOX-MHTML-BOUNDARY"',"Snapshot-Content-Location: "+w].join(`\r
`);return console.log("[generator] Header created:",k),k+`\r
\r
`}function O(q){return q.split("").map((w)=>{let k=w.charCodeAt(0);if(k>127||w==="="||w==="."||w==="\r"||w===`
`)return"="+k.toString(16).toUpperCase().padStart(2,"0");return w}).join("")}function V(q){let w=q.location.href,k=`<meta name="mhtml-location" content="${w}">`,F=`<base href="${w}">`,A=q.documentElement.outerHTML;if(!A.includes("<head"))A=A.replace("<html","<html><head></head>");A=A.replace(/<head[^>]*>/,`$&${k}${F}`),A=`<!DOCTYPE html>
${A}`;let E=O(A),z=["Content-Type: text/html","Content-Transfer-Encoding: quoted-printable","Content-Location: "+w,"",E].join(`\r
`);return console.log("[generator] Main content created with Content-Type: text/html"),console.log("[generator] Content length:",E.length),z}function W(q){let k=[`Content-Type: ${q.contentType.includes("charset=")?q.contentType:`${q.contentType}; charset=utf-8`}`,"Content-Transfer-Encoding: base64","Content-Location: "+q.url,"",q.content].join(`\r
`);return console.log("[generator] Resource part created for:",q.url),k}async function X(q){let w=[],k=new Set,F=q.getElementsByTagName("img");for(let E of F){let z=E.src;if(z&&!z.startsWith("data:")&&!k.has(z))try{let I=await(await fetch(z)).blob(),J=(await Y(I)).split(",")[1];if(J)w.push({url:z,content:J,contentType:I.type||"application/octet-stream"}),k.add(z)}catch(G){console.warn(`Failed to fetch image: ${z}`,G)}}let A=q.styleSheets;for(let E of A)if(E.href&&!k.has(E.href))try{let G=await(await fetch(E.href)).text();w.push({url:E.href,content:btoa(G),contentType:"text/css"}),k.add(E.href)}catch(z){console.warn(`Failed to fetch stylesheet: ${E.href}`,z)}return w}function Y(q){return new Promise((w,k)=>{let F=new FileReader;F.onloadend=()=>w(F.result),F.onerror=k,F.readAsDataURL(q)})}console.log("[content] Content script loaded");browser.runtime.onMessage.addListener((q,w)=>{if(console.log("[content] Received message",{type:q.type,sender:w}),q.type==="capture-mhtml")try{return console.log("[content] Starting MHTML capture..."),console.log("[content] Document title:",document.title),console.log("[content] Document URL:",document.location.href),console.log("[content] Document has images:",document.getElementsByTagName("img").length),console.log("[content] Document has stylesheets:",document.styleSheets.length),K(document).then((k)=>{return console.log("[content] MHTML capture completed, size:",k.byteLength),{success:!0,data:k}}).catch((k)=>{return console.error("[content] MHTML capture failed:",k),{success:!1,error:k instanceof Error?k.message:String(k)}})}catch(k){return console.error("[content] MHTML capture failed (sync):",k),Promise.resolve({success:!1,error:k instanceof Error?k.message:String(k)})}return console.log("[content] Unhandled message type:",q.type),Promise.resolve(void 0)});
